//TYPE

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_NUMBERS = 'GET_NUMBERS';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
